# Generated by Django 3.2.3 on 2021-06-25 10:32

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=polls.models.poll_candidates_image_upload_dir),
        ),
    ]
