# Generated by Django 3.2.3 on 2021-06-25 11:27

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_poll_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=polls.models.poll_image_upload_dir),
        ),
    ]
