# Generated by Django 3.2.3 on 2021-06-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_poll_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
