# Generated by Django 3.2.3 on 2021-06-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_poll_display'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='display',
            new_name='active',
        ),
        migrations.AddField(
            model_name='poll',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
