# Generated by Django 3.2.3 on 2021-06-26 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210625_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pollcategory',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='polls.poll'),
        ),
    ]
