# Generated by Django 3.2.3 on 2021-06-26 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0007_auto_20210626_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='restrictionType',
            field=models.CharField(choices=[('none', 'none'), ('key', 'key'), ('ip', 'ip')], default='none', max_length=30),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=500, null=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll')),
                ('position', models.ManyToManyField(blank=True, null=True, to='polls.PollCategory')),
                ('voter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestrictKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key1', models.CharField(blank=True, max_length=500, null=True)),
                ('key2', models.CharField(blank=True, max_length=500, null=True)),
                ('key_headings', models.CharField(blank=True, max_length=500, null=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='polls.poll')),
            ],
        ),
    ]
