# Generated by Django 3.2.3 on 2021-06-26 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20210626_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.candidate'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='positions_standing',
            field=models.ManyToManyField(blank=True, null=True, related_name='candidates', to='polls.PollCategory'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.poll'),
        ),
    ]
