# Generated by Django 3.2.3 on 2021-06-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20210626_1411'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='restrictkey',
            constraint=models.UniqueConstraint(fields=('poll', 'key1', 'key2'), name='unique key per poll'),
        ),
    ]
