# Generated by Django 3.2.3 on 2021-06-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_restrictkey_unique key per poll'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='restrictkey',
            name='unique key per poll',
        ),
        migrations.RenameField(
            model_name='restrictkey',
            old_name='key1',
            new_name='key',
        ),
        migrations.RemoveField(
            model_name='restrictkey',
            name='key2',
        ),
        migrations.RemoveField(
            model_name='restrictkey',
            name='key_headings',
        ),
        migrations.AddField(
            model_name='restrictkey',
            name='key_heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddConstraint(
            model_name='restrictkey',
            constraint=models.UniqueConstraint(fields=('poll', 'key'), name='unique key per poll'),
        ),
    ]
