# Generated by Django 3.2.3 on 2021-06-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20210626_1449'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pollcategorygroup',
            constraint=models.UniqueConstraint(fields=('poll', 'name'), name='unique category group per poll'),
        ),
    ]
