# Generated by Django 3.2.3 on 2021-06-26 17:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0013_pollcategorygroup_unique category group per poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='positions_standing',
            field=models.ManyToManyField(blank=True, related_name='candidates', to='polls.PollCategory'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='votes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vote',
            name='position',
            field=models.ManyToManyField(blank=True, to='polls.PollCategory'),
        ),
    ]
