# Generated by Django 3.2.3 on 2021-06-27 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_pollcategory_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='votes',
        ),
    ]
