# Generated by Django 3.2.3 on 2021-06-27 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_remove_candidate_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='position',
        ),
        migrations.AddField(
            model_name='vote',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.pollcategory'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('voter', 'poll', 'category'), name='can vote only once in poll category'),
        ),
    ]
