# Generated by Django 3.2.3 on 2021-06-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20210627_2044'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RestrictKey',
            new_name='RestrictionKey',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='key',
        ),
        migrations.AlterField(
            model_name='poll',
            name='restrictionType',
            field=models.CharField(choices=[('none', 'none'), ('oneKey', 'oneKey'), ('specialKey', 'specialKey'), ('ip', 'ip')], default='none', max_length=30),
        ),
    ]
