# Generated by Django 3.2.3 on 2021-06-30 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_alter_vote_candidate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollcategorygroup',
            options={'ordering': ['id']},
        ),
    ]
