# Generated by Django 3.2.3 on 2021-07-07 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_alter_pollcategorygroup_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='picture',
            new_name='image',
        ),
    ]
