# Generated by Django 3.2.3 on 2021-07-07 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_rename_picture_candidate_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='positions_standing',
            new_name='categories_contesting',
        ),
    ]
