# Generated by Django 3.2.3 on 2021-07-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_rename_positions_standing_candidate_categories_contesting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='restrictionType',
            field=models.CharField(blank=True, choices=[('oneKey', 'oneKey'), ('specialKeys', 'specialKeys'), ('ip', 'ip')], max_length=30, null=True),
        ),
    ]
