# Generated by Django 3.2.3 on 2021-07-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_alter_poll_restrictiontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='closing_date',
            field=models.DateField(null=True),
        ),
    ]
