# Generated by Django 3.2.3 on 2021-07-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_poll_closing_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='restrictionkey',
            name='unique key per poll',
        ),
        migrations.RemoveField(
            model_name='restrictionkey',
            name='key',
        ),
        migrations.RemoveField(
            model_name='restrictionkey',
            name='key_heading',
        ),
        migrations.AddField(
            model_name='restrictionkey',
            name='key_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restrictionkey',
            name='key_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='restrictionkey',
            constraint=models.UniqueConstraint(fields=('poll', 'key_1'), name='unique key per poll'),
        ),
    ]
