# Generated by Django 3.2.3 on 2021-07-10 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20210710_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyHeadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_1Heading', models.CharField(blank=True, max_length=500, null=True)),
                ('key_2Heading', models.CharField(blank=True, max_length=500, null=True)),
                ('key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='key_heads', to='polls.poll')),
            ],
        ),
    ]
