# Generated by Django 3.2.3 on 2021-07-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_keyheadings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyheadings',
            old_name='key_1Heading',
            new_name='heading_1',
        ),
        migrations.RenameField(
            model_name='keyheadings',
            old_name='key_2Heading',
            new_name='heading_2',
        ),
    ]
