# Generated by Django 3.2.3 on 2021-07-10 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_auto_20210710_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyheadings',
            name='key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='key_headings', to='polls.poll'),
        ),
    ]
