# Generated by Django 3.2.3 on 2021-07-10 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_alter_keyheadings_key'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='restrictionkey',
            name='unique key per poll',
        ),
        migrations.RemoveField(
            model_name='keyheadings',
            name='heading_1',
        ),
        migrations.RemoveField(
            model_name='keyheadings',
            name='heading_2',
        ),
        migrations.RemoveField(
            model_name='restrictionkey',
            name='key_1',
        ),
        migrations.RemoveField(
            model_name='restrictionkey',
            name='key_2',
        ),
        migrations.AddField(
            model_name='keyheadings',
            name='heading',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='restrictionkey',
            name='key',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='keyheadings',
            name='key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='key_heading', to='polls.poll'),
        ),
        migrations.AddConstraint(
            model_name='restrictionkey',
            constraint=models.UniqueConstraint(fields=('poll', 'key'), name='unique key per poll'),
        ),
    ]
