# Generated by Django 3.2.3 on 2021-07-12 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0030_restrictionkey_usedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='restrictionType',
            field=models.CharField(blank=True, choices=[('oneKey', 'oneKey'), ('specialKeys', 'specialKeys'), ('none', 'none')], default='none', max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='UsedKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.restrictionkey')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
