# Generated by Django 3.2.3 on 2021-07-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0032_auto_20210712_1129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsedKey',
        ),
    ]
