# Generated by Django 3.2.3 on 2021-07-12 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0033_delete_usedkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrictionkey',
            name='allowed',
            field=models.ManyToManyField(blank=True, related_name='oneKey', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restrictionkey',
            name='usedBy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialKey', to=settings.AUTH_USER_MODEL),
        ),
    ]
