# Generated by Django 3.2.3 on 2021-07-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0034_auto_20210712_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['poll']},
        ),
        migrations.AddField(
            model_name='poll',
            name='show_results_while_active',
            field=models.BooleanField(default=False),
        ),
    ]
