# Generated by Django 3.2.3 on 2021-07-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0036_rename_show_results_while_active_poll_live_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='party',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
