# Generated by Django 3.2.3 on 2021-07-20 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0037_candidate_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.pollcategory'),
        ),
    ]
