# Generated by Django 3.2.3 on 2021-07-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0038_alter_vote_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['voter']},
        ),
    ]
