# Generated by Django 3.2.3 on 2021-07-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0039_alter_vote_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeyHeadings',
        ),
    ]
