# Generated by Django 3.2.3 on 2021-07-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0040_delete_keyheadings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
