# Generated by Django 3.2.3 on 2021-07-26 21:54

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0041_alter_poll_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=polls.models.poll_image_upload_dir),
        ),
        migrations.AlterField(
            model_name='poll',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
