# Generated by Django 3.2.3 on 2021-07-27 06:57

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0042_auto_20210726_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=polls.models.poll_candidates_image_upload_dir),
        ),
    ]
