# Generated by Django 3.1.7 on 2021-04-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_other_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pictures',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
