# Generated by Django 3.1.7 on 2021-04-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210407_0920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_pictures',
            new_name='profile_picture',
        ),
    ]
