# Generated by Django 3.1.7 on 2021-04-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210414_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_names',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_names',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
