# Generated by Django 3.1.7 on 2021-05-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210415_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
