# Generated by Django 3.2.3 on 2021-07-27 06:57

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20210722_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=user.models.profile_image_upload_dir),
        ),
    ]
